// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moczqoijpjntqkhulbjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vY3pxb2lqcGpudHFraHVsYmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDM0MDAsImV4cCI6MjA2NTc3OTQwMH0.9LOSMqKLDDcA9kh9ZcPJ-NPlRIscDKyW4ykfu5cDHy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);